[package]
name = "peaq-rpc-debug"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.1.0"

[dependencies]
futures = { workspace = true, default-features = true, features = [ "compat" ] }
hex-literal = { workspace = true, default-features = true }
jsonrpsee = { workspace = true, default-features = true, features = [ "macros", "server" ] }
tokio = { workspace = true, default-features = true, features = [ "sync", "time" ] }

peaq-client-evm-tracing = { path = "../../evm-tracing" }
peaq-rpc-core-debug = { path = "../../rpc-core/debug" }
peaq-rpc-core-types = { path = "../../rpc-core/types" }
peaq-rpc-primitives-debug = { path = "../../../primitives/rpc/debug" }

# Substrate
sc-client-api = { workspace = true, default-features = true }
sc-utils = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-block-builder = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-core = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }

# Frontier
ethereum = { workspace = true, default-features = false, features = [ "with-codec" ] }
ethereum-types = { workspace = true, default-features = true }
fc-consensus = { workspace = true, default-features = true }
fc-db = { workspace = true, default-features = true }
fc-rpc = { workspace = true, default-features = true, features = [ "rpc-binary-search-estimate" ] }
fp-rpc = { workspace = true, default-features = true }
fc-storage = { workspace = true, default-features = true }
fc-api = { workspace = true }
