FROM ubuntu:20.04

WORKDIR /opt/network
ADD target/release/peaq-node /opt/network/peaq-node
ADD target/release/wbuild/peaq-node-runtime/peaq_node_runtime.wasm /opt/network/wasm/peaq_node_runtime.wasm

ENV CHAINSPEC=agung
EXPOSE 9933 9944 1033

CMD /opt/network/peaq-node --ws-external --rpc-external --chain $CHAINSPEC --ethapi=debug,trace,txpool --wasm-runtime-overrides wasm --execution Wasm