//! Prost-generated types from `proto/did_spec_v0.proto` and `proto/did_spec.proto`.
//!
//! The Rust source is written to `OUT_DIR` by `build.rs` (inside `target/`, never committed)
//! and pulled in here at compile time via `include!`.
//!
//! Conversions between prost types and native pallet types (`did_spec::v0::*`) are
//! auto-generated by the `generate_proto_file!` call in `did_spec/v0.rs` — no manual
//! `From`/`TryFrom` impls needed here.

// prost-generated code needs std (Vec, String, …) — gate the whole module accordingly.
#![cfg(feature = "std")]

/// prost-generated types for `package peaq.did.v0`.
pub mod v0 {
    include!(concat!(env!("OUT_DIR"), "/peaq.did.v0.rs"));
}

/// prost-generated types for `package peaq.did` (VersionedDidDocument wrapper).
/// References `v0::DidDocument` via the sibling `v0` module above.
pub use v0 as did_v0; // re-export so that peaq.did.rs can resolve `v0::*` at this level
include!(concat!(env!("OUT_DIR"), "/peaq.did.rs"));
