//! Autogenerated weights for `peaq-pallet-did2`.
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI.
//! Regenerate with:
//!   `peaq-node benchmark pallet --chain=<chain> --pallet=peaq_pallet_did2 --extrinsic='*' ...`

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `peaq_pallet_did2`.
pub struct WeightInfo<T>(PhantomData<T>);

impl<T: frame_system::Config> crate::WeightInfo for WeightInfo<T> {
	/// Storage: `PeaqDid2::Controller` (r:1 w:1)
	/// Storage: `PeaqDid2::Service` (r:0 w:1)
	fn create() -> Weight {
		// Placeholder weights – regenerate via benchmarking CLI before production use.
		Weight::from_parts(10_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}
}
