[package]
name = "peaq-rpc-trace"
authors = ['peaq network <https://github.com/peaqnetwork>']
edition = "2021"
homepage = 'https://peaq.network/'
license = "GPL-3.0-only"
repository = 'https://github.com/peaqnetwork/peaq-network-node/'
version = "0.6.0"

[dependencies]
log = { workspace = true }
ethereum = { workspace = true, default-features = true, features = [ "with-codec" ] }
ethereum-types = { workspace = true, default-features = true }
futures = { workspace = true, default-features = true }
jsonrpsee = { workspace = true, default-features = true, features = [ "macros", "server" ] }
serde = { workspace = true, default-features = true, features = [ "derive" ] }
sha3 = { workspace = true, default-features = true }
tokio = { workspace = true, default-features = true, features = [ "sync", "time" ] }
tracing = { workspace = true, default-features = true }
substrate-prometheus-endpoint = { workspace = true }

peaq-client-evm-tracing = { path = "../../evm-tracing" }
peaq-rpc-core-trace = { path = "../../rpc-core/trace" }
peaq-rpc-core-types = { path = "../../rpc-core/types" }
peaq-rpc-primitives-debug = { path = "../../../primitives/rpc/debug" }

# Substrate
sc-client-api = { workspace = true, default-features = true }
sc-network = { workspace = true, default-features = true }
sc-utils = { workspace = true, default-features = true }
sp-api = { workspace = true, default-features = true }
sp-block-builder = { workspace = true, default-features = true }
sp-blockchain = { workspace = true, default-features = true }
sp-io = { workspace = true, default-features = true }
sp-runtime = { workspace = true, default-features = true }
sp-std = { workspace = true, default-features = true }
sp-transaction-pool = { workspace = true, default-features = true }

# Frontier
fc-consensus = { workspace = true, default-features = true }
fc-rpc = { workspace = true, default-features = true, features = [ "rpc-binary-search-estimate" ] }
fc-rpc-core = { workspace = true, default-features = true }
fp-rpc = { workspace = true, default-features = true }
fc-storage = { workspace = true, default-features = true }
