name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ dev ]
  release:
    types:
      - published

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-node:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-24.04

    steps:
    - name: Get PR number or target branch
      id: tag-title
      run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "This is a pull request."
            echo "target_tag=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "This is a push event."
            echo "target_tag=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT
          else
            echo "Unsupported event: ${{ github.event_name }}"
          fi
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Cache cargo registry
      uses: actions/cache@v4
      with:
        path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
        key: ${{ runner.os }}-cargo-fe438c63458706e034
        restore-keys: |
            ${{ runner.os }}-cargo-
    - name: Compile node
      uses: addnab/docker-run-action@v2
      with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}
        registry: ghcr.io
        image: ghcr.io/peaqnetwork/peaq-node-builder:latest
        options: 
          -v ${{ github.workspace }}:/work
          -v $HOME/.cargo/registry:/usr/local/cargo/registry
          -v $HOME/.cargo/git:/usr/local/cargo/git
          -v ${{ github.workspace }}/target:/work/target
        run: |
          cd /work

          echo "Building wasm"
          cargo build --release -p peaq-runtime --features "std aura on-chain-release-build"

          echo "Building network node"
          cargo build --release --features on-chain-release-build

    - uses: tenhaus/get-release-or-tag@v2
      id: tag

    - name: Compress peaq node
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ./target/release/
        files: |
          ./peaq-node
        outPath: peaq-node-${{ steps.tag.outputs.tag }}.tar.gz

    - name: Compress wasm runtime
      uses: a7ul/tar-action@v1.1.0
      with:
        command: c
        cwd: ./target/release/wbuild/peaq-runtime/
        files: |
          ./peaq_runtime.compact.compressed.wasm
        outPath: peaq-node-runtime-${{ steps.tag.outputs.tag }}.tar.gz

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.tag-title.outputs.target_tag }}
        draft: true
        files: |
          peaq-node-${{ steps.tag.outputs.tag }}.tar.gz
          peaq-node-runtime-${{ steps.tag.outputs.tag }}.tar.gz

