name: Pull Request Check

on:
  pull_request:
    types:
      - opened
      - synchronize
      - closed

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fmt:
    runs-on: ubuntu-latest
    container:
      image: rust:1.87-slim
    
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      
      - name: "[Check] cargo fmt"
        run: cargo fmt --check

  test-and-clippy:
    runs-on: ubuntu-latest
    container:
      image: paritytech/ci-linux:production
    
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v5
      
      - name: Fix permissions
        run: |
          # Fix permission issues with the rustup directory
          mkdir -p ~/.cargo ~/.rustup
          chown -R $(whoami):$(whoami) ~/.cargo ~/.rustup
      
      - name: Cache build outputs
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            
      - name: Run tests
        run: |
          RUST_BACKTRACE=1 cargo test --release --features on-chain-release-build -v
            
      - name: Run clippy
        run: |
          cargo clippy --release --features on-chain-release-build -- -Dwarnings
